name: PR Build

on: pull_request

env:
  RUN_JOBS: ${{ github.repository == 'spring-projects/spring-security' }}

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - if: env.RUN_JOBS == 'true'
        uses: actions/checkout@v2
      - name: Set up gradle
        uses: spring-io/spring-gradle-build-action@v1
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        if: env.RUN_JOBS == 'true'
        run: ./gradlew clean build --continue --scan
